### PR TITLE
Trailing slash in web dir

### LINKED ISSUE #12: Trailing slash in badge directory
The script currently points to:
https://raw.githubusercontent.com/LSSTDESC/beavis-ci/master/badges/

However, GitHub reports:
```
400: Invalid request
```

Is this the correct URL now?
https://github.com/LSSTDESC/beavis-ci/raw/master/badges/

### PR DESCRIPTION
**Pull request by kadrlica**
Closes #12

### CODE REVIEW

**Review by yymao — APPROVED** [review]
Thanks for catching this.

**Comment by kadrlica** [comment]
Thanks Yao, I don't think I can merge.

**Comment by yymao** [comment]
Hmmm. Merging now and will check setting.

**Comment by yymao** [comment]
Hmm, I don't think I can check settings :sweat_smile:

**Pull request merged**
